### ISSUE TITLE
Feature request: ability to retain custom artboard labels

### ISSUE THREAD

**Issue by salux** [elihorne/smartboards#4]
I often create full page mocks from artboards in a project and use the naming feature to label and sort them out ("mocks/landing_page", "icons/app_icon-72px", etc.). It would be super cool if there was a way to keep the functionality but still retain the sorting abilities. It seems like you're able to do the sorting based purely on layout positioning, so perhaps there could be an option that doesn't touch the artboard labels... or a version that appends them to the end of the artboard label?

Thanks for a great plugin!

**Comment by elihorne** [comment]
It would probably be easiest to add a separate command which organizes but
doesn't label. The labels are mostly for exporting so that they show up in
an index as expected (alphabetically and then numerically)

Alternatively, I could preserve the labels at the end but I'd need some
kind of pattern to look for like "[A01] - your label" but that probably
doesn't achieve what you are looking for.

Thanks for the feedback! I'll try to get this integrated

**Comment by awish** [comment]
I completely agree and would love a new command that doesn't rename.  Love this plugin, thanks so much for creating it.

**Comment by elihorne** [comment]
Hey @salux and @awish - I just updated the plugin to have a new feature which will only align the artboards without touching the naming.  Take a look and let me know if it does what you want. 

The keyboard shortcut is shift+command+option+g

**Comment by awish** [comment]
@elihorne 
ARE YOU A SAINT?  ...A MAGICAL UNICORN? 
This is my way of saying yes, it does exactly what I want and it's brilliant!

Thanks so much!

**Comment by elihorne** [comment]
@awish glad to help!
