### ISSUE TITLE
REQ : Inverse main alignement

### ISSUE THREAD

**Issue by rodnem** [elihorne/smartboards#9]
I would like to choose whether I align my main flow vertically or horizontally.

In fact, I always arrange my artboards from left to right (and not top to bottom) with variants and alternatives under the first artboards
![pasted_image_12_06_2017__15_54](https://user-images.githubusercontent.com/6350513/27037281-bd82d638-4f87-11e7-98af-8f7c7e600296.jpg)

**Comment by elihorne** [comment]
That's beyond the scope of what I want to do with this plugin, but please
feel free to fork my code.


On Jun 12, 2017 at 8:57 AM, nemrod <notifications@github.com> wrote:


I would like to choose whether I align my main flow vertically or
horizontally.

In fact, I always arrange my artboards from left to right (and not top to
bottom) with variants and alternatives under the first artboards
[image: pasted_image_12_06_2017__15_54]
<https://user-images.githubusercontent.com/6350513/27037281-bd82d638-4f87-11e7-98af-8f7c7e600296.jpg>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/elihorne/smartboards/issues/9>, or mute the thread
